# https://taskfile.dev
version: '3'
tasks:
  test:
    desc: run test
    cmds:
      - go test ./...

  install:
    desc: build and install to go/bin
    cmds:
      - go build -o ~/go/bin/tool cmd/*.go
